export interface MenuItem {
  name: string;
  description: string;
  descriptionEn: string;
  descriptionPt: string;
  price: string;
  chefPick?: boolean;
  winePairing?: string;
  image?: string;
}

export interface MenuCategory {
  id: string;
  name: string;
  nameEn: string;
  namePt: string;
  items: MenuItem[];
}

export const menuCategories: MenuCategory[] = [
  {
    id: 'entrees-froides',
    name: 'Entrées Froides',
    nameEn: 'Cold Starters',
    namePt: 'Entradas Frias',
    items: [
      { name: 'Roulade de Jambon', description: 'Roulade de jambon maison', descriptionEn: 'Homemade ham roulade', descriptionPt: 'Roulade de presunto artesanal', price: '$$' },
      { name: 'Tartare au Saumon', description: 'Tartare de saumon frais, accras', descriptionEn: 'Fresh salmon tartare', descriptionPt: 'Tartare de salmão fresco, acras', price: '$$' },
      { name: 'Saumon Fumé', description: 'Saumon fumé maison, garniture traditionnelle', descriptionEn: 'House-smoked salmon, traditional garnish', descriptionPt: 'Salmão defumado artesanal, acompanhamento tradicional', price: '$$' },
      { name: 'Foie Gras de Canard', description: 'Foie gras de canard, confiture de fruits', descriptionEn: 'Duck foie gras, fruit jam', descriptionPt: 'Foie gras de pato, geleia de frutas', price: '$$$', chefPick: true },
      { name: 'Tomate Mozzarella', description: 'Tomates fraîches, mozzarella, basilic, huile d\'olive', descriptionEn: 'Fresh tomatoes, mozzarella, basil, olive oil', descriptionPt: 'Tomates frescas, muçarela, manjericão, azeite de oliva', price: '$' },
      { name: 'Salade de Pieuvre', description: 'Salade de pieuvre grillée, vinaigrette agrumes', descriptionEn: 'Grilled octopus salad, citrus vinaigrette', descriptionPt: 'Salada de polvo grelhado, vinagrete de citros', price: '$$' },
      { name: 'Cocktail de Cossas', description: 'Cocktail de cossas frais, sauce maison', descriptionEn: 'Fresh cossas cocktail, homemade sauce', descriptionPt: 'Coquetel de cossas frescos, molho caseiro', price: '$$' },
      { name: 'Tomates aux Cossas', description: 'Tomates garnies de cossas, sauce cocktail', descriptionEn: 'Tomatoes stuffed with cossas, cocktail sauce', descriptionPt: 'Tomates recheadas com cossas, molho cocktail', price: '$$' },
      { name: 'Oeufs à la Russe', description: 'Oeufs à la russe, mayonnaise maison', descriptionEn: 'Russian eggs, homemade mayonnaise', descriptionPt: 'Ovos à russa, maionese caseira', price: '$' },
      { name: 'Salade Niçoise', description: 'Salade niçoise traditionnelle, thon, olives, œufs', descriptionEn: 'Traditional Niçoise salad, tuna, olives, eggs', descriptionPt: 'Salada nicoise tradicional, atum, azeitonas, ovos', price: '$$' },
      { name: 'Salade Verte', description: 'Salade verte fraîche, vinaigrette', descriptionEn: 'Fresh green salad, vinaigrette', descriptionPt: 'Salada verde fresca, vinagrete', price: '$' },
      { name: 'Salade Mixte', description: 'Salade mixte de légumes frais', descriptionEn: 'Mixed fresh vegetable salad', descriptionPt: 'Salada mista de legumes frescos', price: '$' },
      { name: 'Cossa/Gambas Croquant', description: 'Cossas et gambas croustillants, sauce aïl pili', descriptionEn: 'Crispy cossas and prawns, garlic pili sauce', descriptionPt: 'Cossas e gambas crocantes, molho de alho e pili', price: '$$', chefPick: true },
      { name: 'Crème de Cossa', description: 'Crème onctueuse de cossa, touché d\'épices', descriptionEn: 'Smooth cossa cream, touch of spices', descriptionPt: 'Creme aveludado de cossa, toque de especiarias', price: '$$', chefPick: true },
      { name: 'Noix de Saint Jacques au Porc Ibérico', description: 'Saint-jacques poêlées, porc ibérico finement tranché', descriptionEn: 'Pan-seared scallops, finely sliced Iberico pork', descriptionPt: 'Vieiras na chapa, presunto ibérico finamente fatiado', price: '$$$' },
      { name: 'Salade Grecque à la Feta', description: 'Salade grecque traditionnelle, feta crémeuse, olives kalamata', descriptionEn: 'Traditional Greek salad, creamy feta, Kalamata olives', descriptionPt: 'Salada grega tradicional, feta cremosa, azeitonas kalamata', price: '$' },
      { name: 'Caviar', description: 'Caviar d\'exception, service traditionnel, blinis et crème fraîche', descriptionEn: 'Exceptional caviar, traditional service, blinis and crème fraîche', descriptionPt: 'Caviar de exceção, serviço tradicional, blinis e creme fraîche', price: '$$$$', chefPick: true },
    ],
  },
  {
    id: 'entrees-chaudes',
    name: 'Entrées Chaudes',
    nameEn: 'Hot Starters',
    namePt: 'Entradas Quentes',
    items: [
      { name: '6 Escargots de Bourgogne', description: '6 escargots de Bourgogne, beurre à l\'ail et persil', descriptionEn: '6 Burgundy escargots, garlic and parsley butter', descriptionPt: '6 caracóis da Borgonha, manteiga de alho e salsinha', price: '$$' },
      { name: 'Chouriço Grillé Portugal', description: 'Chouriço portugais grillé, flambé à la table', descriptionEn: 'Grilled Portuguese chouriço, tableside flambé', descriptionPt: 'Chouriço português grelhado, flambeado na mesa', price: '$$', chefPick: true },
      { name: 'Croquettes de Morue ou Crevette', description: 'Croquettes de morue ou de crevettes, sauce maison', descriptionEn: 'Cod or shrimp croquettes, homemade sauce', descriptionPt: 'Croquetas de bacalhau ou camarão, molho caseiro', price: '$$' },
      { name: 'Coquille de Poisson', description: 'Coquille de poisson farcie, gratinée', descriptionEn: 'Stuffed fish scallop, gratiné', descriptionPt: 'Concha de peixe recheada, gratinada', price: '$$' },
      { name: 'Beignets de Cossas', description: 'Beignets de cossas croustillants, sauce cocktail', descriptionEn: 'Crispy cossas fritters, cocktail sauce', descriptionPt: 'Beignets de cossas crocantes, molho cocktail', price: '$$' },
      { name: 'Cossas Special "Chez Gaby"', description: 'Cossas façon Chez Gaby, sauce secrète', descriptionEn: 'Cossas Chez Gaby style, secret sauce', descriptionPt: 'Cossas ao estilo Chez Gaby, molho secreto', price: '$$$', chefPick: true },
      { name: 'Cuisses de Grenouilles', description: 'Cuisses de grenouilles poêlées, beurre à l\'ail', descriptionEn: 'Pan-fried frog legs, garlic butter', descriptionPt: 'Coxinhas de rã na chapa, manteiga de alho', price: '$$$' },
      { name: 'Croque Madame/Monsieur', description: 'Croque madame ou monsieur, frites maison', descriptionEn: 'Croque madame or monsieur, homemade fries', descriptionPt: 'Croque madame ou monsieur, batatas fritas caseiras', price: '$$' },
      { name: 'Les Toastes aux Champignons', description: 'Toasts garnis de champignons sautés, fromage fondu', descriptionEn: 'Toasts with sautéed mushrooms, melted cheese', descriptionPt: 'Tostas com cogumelos salteados, queijo derretido', price: '$$' },
      { name: 'Aubergines Farcies', description: 'Aubergines farcies de viande, gratinées', descriptionEn: 'Stuffed aubergines with meat, gratiné', descriptionPt: 'Berinjelas recheadas com carne, gratinadas', price: '$$' },
    ],
  },
  {
    id: 'poissons',
    name: 'Poissons',
    nameEn: 'Fish',
    namePt: 'Peixes',
    items: [
      { name: 'Capitaine', description: 'Capitaine braisé, riz parfumé', descriptionEn: 'Braised Nile perch, fragrant rice', descriptionPt: 'Capitão braseado, arroz perfumado', price: '$$$' },
      { name: 'Capitaine Grillé', description: 'Capitaine grillé, légumes de saison', descriptionEn: 'Grilled Nile perch, seasonal vegetables', descriptionPt: 'Capitão grelhado, legumes da estação', price: '$$$' },
      { name: 'Brochette de Capitaine', description: 'Brochette de capitaine mariné, sauce teriyaki, riz', descriptionEn: 'Marinated Nile perch brochette, teriyaki sauce, rice', descriptionPt: 'Brocheto de capitão marinado, molho teriyaki, arroz', price: '$$$' },
      { name: 'Filet de Capitaine', description: 'Filet de capitaine grillé, beurre citronné, légumes', descriptionEn: 'Grilled Nile perch fillet, lemon butter, vegetables', descriptionPt: 'Filé de capitão grelhado, manteiga de limão, legumes', price: '$$$' },
      { name: 'Les Coquilles de Saint Jacques au Beurre Blanc', description: 'Saint-jacques poêlées, sauce beurre blanc', descriptionEn: 'Pan-seared scallops, white butter sauce', descriptionPt: 'Vieiras na chapa, molho beurre blanc', price: '$$$$', chefPick: true },
      { name: 'Filet de King Klip', description: 'Filet de king klip grillé, sauce au choix', descriptionEn: 'Grilled king klip fillet, choice of sauce', descriptionPt: 'Filé de king klip grelhado, molho à escolha', price: '$$$' },
      { name: 'Riz aux Fruits de Mer', description: 'Riz parfumé aux fruits de mer frais', descriptionEn: 'Fragrant rice with fresh seafood', descriptionPt: 'Arroz perfumado com frutos do mar frescos', price: '$$$' },
      { name: 'Riz de Pieuvre', description: 'Riz à la pieuvre grillée, sauce tomate', descriptionEn: 'Rice with grilled octopus, tomato sauce', descriptionPt: 'Arroz com polvo grelhado, molho de tomate', price: '$$$' },
      { name: 'Morue Grillée ou Bouillie avec Légumes', description: 'Morue grillée ou bouillie, légumes de saison', descriptionEn: 'Grilled or boiled cod, seasonal vegetables', descriptionPt: 'Bacalhau grelhado ou cozido, legumes da estação', price: '$$$' },
      { name: 'Morue à Braz', description: 'Morue à la mode de Braz, riz parfumé', descriptionEn: 'Braz-style cod, fragrant rice', descriptionPt: 'Bacalhau ao estilo Braz, arroz perfumado', price: '$$$' },
      { name: 'Calderade de Morue', description: 'Calderade de morue traditionnelle', descriptionEn: 'Traditional cod calderade', descriptionPt: 'Calderada de bacalhau tradicional', price: '$$$' },
      { name: 'Cossas Gaby Plat', description: 'Cossas façon Gaby, riz parfumé', descriptionEn: 'Cossas Gaby style, fragrant rice', descriptionPt: 'Cossas ao estilo Gaby, arroz perfumado', price: '$$$', chefPick: true },
      { name: 'Cossas Zélia', description: 'Cossas à la Zélia, sauce crémeuse', descriptionEn: 'Cossas Zélia style, creamy sauce', descriptionPt: 'Cossas ao estilo Zélia, molho cremoso', price: '$$$' },
      { name: 'Cossas Moyenne Plat', description: 'Cossas moyenne, riz et légumes', descriptionEn: 'Medium cossas, rice and vegetables', descriptionPt: 'Cossas médio, arroz e legumes', price: '$$$' },
      { name: 'Cossas Royal', description: 'Cossas royal, sauce champagne', descriptionEn: 'Royal cossas, champagne sauce', descriptionPt: 'Cossas royal, molho champagne', price: '$$$$', chefPick: true },
      { name: 'Langouste au Beurre Blanc ou Nature', description: 'Langouste grillée, beurre blanc ou nature', descriptionEn: 'Grilled lobster, white butter sauce or natural', descriptionPt: 'Lagosta grelhada, molho beurre blanc ou natural', price: '$$$$' },
      { name: 'Sole Meunière', description: 'Sole meunière, beurre de citron, pommes de terre sautées', descriptionEn: 'Sole meunière, lemon butter, sautéed potatoes', descriptionPt: 'Solha meunière, manteiga de limão, batatas salteadas', price: '$$$$', chefPick: true },
      { name: 'Le Bar', description: 'Bar de ligne, cuisson au choix', descriptionEn: 'Line-caught sea bass, choice of cooking', descriptionPt: 'Robalo da linha, ponto de cozimento à escolha', price: '$$$' },
      { name: 'Filet de Sole Panne', description: 'Filet de sole poêlé, beurre noisette', descriptionEn: 'Pan-seared sole fillet, brown butter', descriptionPt: 'Filé de solha na chapa, manteiga avellã', price: '$$$' },
      { name: 'Poissons au Four', description: 'Poisson entier au four, herbes aromatiques', descriptionEn: 'Whole baked fish, aromatic herbs', descriptionPt: 'Peixe inteiro assado, ervas aromáticas', price: '$$$' },
      { name: 'Calamars Sévillhana', description: 'Calamars à la sévillana, riz safran', descriptionEn: 'Squid Sévillana style, saffron rice', descriptionPt: 'Lulas à moda sevilhana, arroz com açafrão', price: '$$$' },
      { name: 'Calamars Grillé', description: 'Calamars grillés, citron et huile d\'olive', descriptionEn: 'Grilled squid, lemon and olive oil', descriptionPt: 'Lulas grelhadas, limão e azeite de oliva', price: '$$$' },
      { name: 'Dorade Braisée', description: 'Dorade royale braisée, légumes de saison, jus d\'herbes', descriptionEn: 'Braised royal sea bream, seasonal vegetables, herb jus', descriptionPt: 'Dourada real braseada, legumes da estação, caldo de ervas', price: '$$$' },
      { name: 'Bar Braisé', description: 'Bar braisé, sauce beurre blanc, purée de pommes de terre', descriptionEn: 'Braised sea bass, white butter sauce, potato purée', descriptionPt: 'Robalo braseado, molho beurre blanc, purê de batatas', price: '$$$' },
      { name: "Sole d'Ostende", description: "Sole meunière, beurre de citron, pommes de terre sautées", descriptionEn: 'Sole meunière, lemon butter, sautéed potatoes', descriptionPt: 'Solha de Ostenda, manteiga de limão, batatas salteadas', price: '$$$$', chefPick: true },
      { name: 'Jeûne Capitaine', description: 'Capitaine braisé, riz parfumé, sauce aux épices', descriptionEn: 'Braised Nile perch, fragrant rice, spiced sauce', descriptionPt: 'Capitão braseado, arroz perfumado, molho apimentado', price: '$$$' },
    ],
  },
  {
    id: 'viandes',
    name: 'Viandes',
    nameEn: 'Meat',
    namePt: 'Carnes',
    items: [
      { name: 'Filet', description: 'Filet de bœuf grillé, sauce au choix', descriptionEn: 'Grilled beef filet, choice of sauce', descriptionPt: 'Filé de carne grelhado, molho à escolha', price: '$$$' },
      { name: 'Filet à la Bière', description: 'Filet de bœuf, sauce à la bière artisanale', descriptionEn: 'Beef filet, craft beer sauce', descriptionPt: 'Filé de carne, molho de cerveja artesanal', price: '$$$' },
      { name: 'Filet Américain', description: 'Filet de bœuf américain, frites maison', descriptionEn: 'American-style beef filet, homemade fries', descriptionPt: 'Filé de carne à americana, batatas fritas caseiras', price: '$$$' },
      { name: 'Filet Gaby', description: 'Filet signature Gaby, sauce secrète', descriptionEn: 'Gaby signature filet, secret sauce', descriptionPt: 'Filé assinatura Gaby, molho secreto', price: '$$$', chefPick: true },
      { name: 'Filet Forestier', description: 'Filet de bœuf, sauce forestière aux champignons', descriptionEn: 'Beef filet, mushroom forestière sauce', descriptionPt: 'Filé de carne, molho floresta com cogumelos', price: '$$$' },
      { name: 'Brochettes Viande', description: 'Brochettes de viande marinées, riz parfumé', descriptionEn: 'Marinated meat skewers, fragrant rice', descriptionPt: 'Espetinhos de carne marinados, arroz perfumado', price: '$$' },
      { name: 'Entrecôte', description: 'Entrecôte grillée, sauce au choix, frites maison', descriptionEn: 'Grilled rib steak, choice of sauce, homemade fries', descriptionPt: 'Bife de costela grelhado, molho à escolha, batatas fritas caseiras', price: '$$$' },
      { name: 'Bitoque Special', description: 'Bitoque spécial, œuf au plat, frites', descriptionEn: 'Special bitoque, fried egg, fries', descriptionPt: 'Bitoque especial, ovo frito, batatas fritas', price: '$$' },
      { name: 'Côtes de Porc', description: 'Côtes de porc grillées, sauce au choix', descriptionEn: 'Grilled pork cutlets, choice of sauce', descriptionPt: 'Costeletas de porco grelhadas, molho à escolha', price: '$$' },
      { name: 'Cochon de Lait', description: 'Cochon de lait rôti, légumes rôtis', descriptionEn: 'Roasted suckling pig, roasted vegetables', descriptionPt: 'Leitão assado, legumes assados', price: '$$$' },
      { name: 'Escalope Cordon Bleu', description: 'Escalope cordon-bleu, frites maison', descriptionEn: 'Cordon bleu escalope, homemade fries', descriptionPt: 'Escalope cordon-bleu, batatas fritas caseiras', price: '$$' },
      { name: 'Escalope Gratinnée aux Champignons', description: 'Escalope gratinée, sauce champignons', descriptionEn: 'Gratiné escalope, mushroom sauce', descriptionPt: 'Escalope gratinada, molho de cogumelos', price: '$$' },
      { name: 'Escalope Milanaise', description: 'Escalope milanaise, riz ou frites', descriptionEn: 'Milanese escalope, rice or fries', descriptionPt: 'Escalope milanesa, arroz ou batatas fritas', price: '$$' },
      { name: 'Escalope de Veau', description: 'Escalope de veau poêlée, beurre noisette', descriptionEn: 'Pan-seared veal escalope, brown butter', descriptionPt: 'Escalope de vitela na chapa, manteiga avellã', price: '$$$' },
      { name: 'Côtes de Veau', description: 'Côtes de veau grillées, sauce au choix', descriptionEn: 'Grilled veal cutlets, choice of sauce', descriptionPt: 'Costeletas de vitela grelhadas, molho à escolha', price: '$$$' },
      { name: 'Osso Buco', description: 'Osso buco mijoté, polenta crémeuse', descriptionEn: 'Braised osso buco, creamy polenta', descriptionPt: 'Osso buco braseado, polenta cremosa', price: '$$$', chefPick: true },
      { name: "Côtelette d'Agneau Marco Polo", description: "Côtelette d'agneau, sauce Marco Polo aux herbes", descriptionEn: 'Lamb chop, Marco Polo herb sauce', descriptionPt: 'Costeleta de cordeiro, molho Marco Polo de ervas', price: '$$$' },
      { name: "Carré d'Agneau", description: "Carré d'agneau rôti, flageolets, sauce persillade", descriptionEn: 'Roasted rack of lamb, flageolet beans, persillade sauce', descriptionPt: 'Cordeiro assado no espeto, feijão flageolet, molho persillade', price: '$$$' },
      { name: 'Jambonneau de Porc', description: 'Jambonneau de porc confit, purée de pommes de terre', descriptionEn: 'Confit pork knuckle, potato purée', descriptionPt: 'Joelho de porco confitado, purê de batatas', price: '$$' },
      { name: 'Entrecôte de Belgique', description: 'Entrecôte belge grillée, sauce au choix, frites maison', descriptionEn: 'Grilled Belgian ribeye, choice of sauce, homemade fries', descriptionPt: 'Bife de costela belga grelhado, molho à escolha, batatas fritas caseiras', price: '$$$' },
      { name: 'Tomahawk de Porc', description: 'Tomahawk de porc confit, miel et épices, légumes rôtis', descriptionEn: 'Pork tomahawk confit, honey and spices, roasted vegetables', descriptionPt: 'Tomahawk de porco confitado, mel e especiarias, legumes assados', price: '$$$' },
      { name: 'Tomahawk de Bœuf', description: 'Tomahawk de bœuf grillé, sauce poivre noir, frites', descriptionEn: 'Grilled beef tomahawk, black pepper sauce, fries', descriptionPt: 'Tomahawk de carne grelhado, molho de pimenta do reino, batatas fritas', price: '$$$$', chefPick: true },
      { name: 'Wagyu-o, 200g', description: 'Wagyu A5, 200g, sauce truffée, légumes de saison', descriptionEn: 'Wagyu A5, 200g, truffle sauce, seasonal vegetables', descriptionPt: 'Wagyu A5, 200g, molho de trufas, legumes da estação', price: '$$$$', chefPick: true },
      { name: "Souris d'Agneau", description: "Souris d'agneau confite, miel et romarin, purée de patate douce", descriptionEn: 'Lamb shank confit, honey and rosemary, sweet potato purée', descriptionPt: 'Pernil de cordeiro confitado, mel e alecrim, purê de batata-doce', price: '$$$' },
      { name: "Gigot d'Agneau", description: "Gigot d'agneau rôti, flageolets, sauce persillade", descriptionEn: 'Roasted leg of lamb, flageolet beans, persillade sauce', descriptionPt: 'Pernil de cordeiro assado, feijão flageolet, molho persillade', price: '$$$' },
      { name: "Côte à l'Os", description: "Côte de bœuf maturée, sauce béarnaise, frites", descriptionEn: 'Aged bone-in ribeye, béarnaise sauce, fries', descriptionPt: 'Costela de carne maturada, molho bernard, batatas fritas', price: '$$$$', chefPick: true },
      { name: "T'Bone", description: 'T\'Bone grillé, légumes grillés, sauce au choix', descriptionEn: 'Grilled T-bone steak, grilled vegetables, choice of sauce', descriptionPt: 'Bife T-Bone grelhado, legumes grelhados, molho à escolha', price: '$$$$', chefPick: true },
      { name: 'Le Filet Rossini', description: 'Filet de bœuf Rossini, escalope de foie gras, sauce truffée', descriptionEn: 'Beef filet Rossini, foie gras escalope, truffle sauce', descriptionPt: 'Filé Rossini de carne, escalope de foie gras, molho de trufas', price: '$$$$', chefPick: true },
      { name: "Le Filet Crème d'Épinard", description: 'Filet de bœuf, crème d\'épinard, pommes de terre', descriptionEn: 'Beef filet, spinach cream, potatoes', descriptionPt: 'Filé de carne, creme de espinafre, batatas', price: '$$$' },
      { name: 'Le Filet Sauce Gorgonzola ou Roquefort', description: 'Filet de bœuf, sauce gorgonzola ou roquefort', descriptionEn: 'Beef filet, Gorgonzola or Roquefort sauce', descriptionPt: 'Filé de carne, molho gorgonzola ou roquefort', price: '$$$' },
      { name: 'Le Tournedos Mexicaine', description: 'Tournedos de bœuf, style mexicaine, épices douces', descriptionEn: 'Beef tournedos, Mexican style, mild spices', descriptionPt: 'Tournedos de carne, à mexicana, especiarias suaves', price: '$$$' },
      { name: 'Le Filet Parmegiani', description: 'Filet de bœuf parmesan, gratiné', descriptionEn: 'Parmesan beef filet, gratiné', descriptionPt: 'Filé de carne à parmegiana, gratinado', price: '$$$' },
      { name: 'Le Filet aux Échalotes', description: 'Filet de bœuf, sauce aux échalotes', descriptionEn: 'Beef filet, shallot sauce', descriptionPt: 'Filé de carne, molho de cebolinha', price: '$$$' },
    ],
  },
  {
    id: 'volailles',
    name: 'Volailles',
    nameEn: 'Poultry',
    namePt: 'Aves',
    items: [
      { name: 'Magret de Canard', description: 'Magret de canard rôti, sauce aux fruits rouges, légumes glacés', descriptionEn: 'Roasted duck breast, red berry sauce, glazed vegetables', descriptionPt: 'Peito de pato assado, molho de frutas vermelhas, legumes caramelizados', price: '$$$' },
      { name: 'Poussin Braisé', description: 'Poussin fermier braisé, herbes aromatiques, jus réduit', descriptionEn: 'Braised farm chicken, aromatic herbs, reduced jus', descriptionPt: 'Frango caipira braseado, ervas aromáticas, caldo reduzido', price: '$$' },
    ],
  },
  {
    id: 'fruits-de-mer',
    name: 'Fruits de Mer',
    nameEn: 'Seafood',
    namePt: 'Frutos do Mar',
    items: [
      { name: 'Plateau de Fruits de Mer', description: 'Plateau royal de fruits de mer frais, citron et sauce maison', descriptionEn: 'Royal platter of fresh seafood, lemon and homemade sauce', descriptionPt: 'Tabua real de frutos do mar frescos, limão e molho caseiro', price: '$$$$', chefPick: true },
      { name: 'Riz aux Gambas NATKAZ', description: 'Riz parfumé aux gambas, sauce NATKAZ signature', descriptionEn: 'Fragrant rice with prawns, NATKAZ signature sauce', descriptionPt: 'Arroz perfumado com gambas, molho assinatura NATKAZ', price: '$$$' },
      { name: 'Pieuvre à la LORENA à l\'ail ou pili', description: 'Pieuvre grillée, sauce LORENA, à l\'ail ou au pili', descriptionEn: 'Grilled octopus, LORENA sauce, garlic or pili pepper', descriptionPt: 'Polvo grelhado, molho LORENA, com alho ou pili', price: '$$$' },
      { name: 'Homard', description: 'Homard grillé, beurre à l\'ail, légumes sautés', descriptionEn: 'Grilled lobster, garlic butter, sautéed vegetables', descriptionPt: 'Lagosta grelhada, manteiga de alho, legumes salteados', price: '$$$$' },
      { name: 'Pince Royale de Crabe', description: 'Pinces de crabe royal, mayonnaise maison, citron', descriptionEn: 'King crab legs, homemade mayonnaise, lemon', descriptionPt: 'Talheres de caranguejo real, maionese caseira, limão', price: '$$$$' },
      { name: 'Saint Jacques façon NATHALIE à l\'ail ou pili', description: 'Saint-jacques poêlées, sauce crémeuse NATHALIE, à l\'ail ou au pili', descriptionEn: 'Pan-seared scallops, creamy NATHALIE sauce, garlic or pili pepper', descriptionPt: 'Vieiras na chapa, molho cremoso NATHALIE, com alho ou pili', price: '$$$' },
      { name: 'Spaghetti LÉONCY à la Truffe', description: 'Spaghetti à la truffe noire, façon LÉONCY, parmesan frais', descriptionEn: 'Black truffle spaghetti, LÉONCY style, fresh parmesan', descriptionPt: 'Espaguete à trufa negra, ao estilo LÉONCY, parmesão fresco', price: '$$$$', chefPick: true },
      { name: 'Tagliatelle PITCHOU à la Crème de Cossa', description: 'Tagliatelles fraîches, crème de cossa, façon PITCHOU', descriptionEn: 'Fresh tagliatelle, cossa cream, PITCHOU style', descriptionPt: 'Tagliatelles frescas, creme de cossas, ao estilo PITCHOU', price: '$$$' },
      { name: 'Gambas Tiger', description: 'Gambas tiger grillées, riz parfumé', descriptionEn: 'Grilled tiger prawns, fragrant rice', descriptionPt: 'Gambas tiger grelhadas, arroz perfumado', price: '$$$' },
    ],
  },
  {
    id: 'autres',
    name: 'Autres',
    nameEn: 'Others',
    namePt: 'Outros',
    items: [
      { name: 'Pregos Normal ou Special', description: 'Pregos portugais, normal ou special', descriptionEn: 'Portuguese pregos, normal or special', descriptionPt: 'Pregos portugueses, normal ou especial', price: '$$' },
      { name: 'Pregos Assiette', description: 'Pregos en assiette, frites maison', descriptionEn: 'Pregos on a plate, homemade fries', descriptionPt: 'Pregos no prato, batatas fritas caseiras', price: '$$' },
      { name: 'Pregos Assiette Champignon', description: 'Pregos assiette, sauce champignons', descriptionEn: 'Pregos plate, mushroom sauce', descriptionPt: 'Pregos no prato, molho de cogumelos', price: '$$' },
      { name: 'Cailles Grillées', description: 'Cailles grillées, herbes aromatiques', descriptionEn: 'Grilled quail, aromatic herbs', descriptionPt: 'Codornizes grelhadas, ervas aromáticas', price: '$$' },
      { name: '½ Poulet Grillé', description: 'Demi-poulet grillé, frites ou riz', descriptionEn: 'Half roasted chicken, fries or rice', descriptionPt: 'Meio frango grelhado, batatas fritas ou arroz', price: '$$' },
      { name: 'Spaghetti Bolognaise', description: 'Spaghetti à la bolognaise maison', descriptionEn: 'Spaghetti with homemade bolognaise', descriptionPt: 'Espaguete à bolonhesa caseira', price: '$$' },
      { name: 'Lasagne Maison Viande ou Légumes', description: 'Lasagne maison au choix : viande ou légumes', descriptionEn: 'House lasagne, choice of meat or vegetables', descriptionPt: 'Lasanha caseira à escolha: carne ou legumes', price: '$$' },
      { name: 'Feijoada Cassoulet', description: 'Feijoada cassoulet traditionnelle', descriptionEn: 'Traditional feijoada cassoulet', descriptionPt: 'Feijoada cassoulet tradicional', price: '$$' },
      { name: 'Demi Plat', description: 'Demi-portion de plat au choix', descriptionEn: 'Half portion of any dish', descriptionPt: 'Meia porção de prato à escolha', price: '$' },
    ],
  },
  {
    id: 'desserts',
    name: 'Desserts',
    nameEn: 'Desserts',
    namePt: 'Sobremesas',
    items: [
      { name: 'Mousse au Chocolat', description: 'Mousse au chocolat noir, chantilly maison', descriptionEn: 'Dark chocolate mousse, homemade whipped cream', descriptionPt: 'Mousse de chocolate amargo, chantilly caseiro', price: '$$' },
      { name: 'Crêpes au Sucre', description: 'Crêpes traditionnelles au sucre', descriptionEn: 'Traditional sugar crepes', descriptionPt: 'Crepes tradicionais com açúcar', price: '$' },
      { name: 'Crêpes Comédie Flambée', description: 'Crêpes flambées au Grand Marnier', descriptionEn: 'Crepes flambéed with Grand Marnier', descriptionPt: 'Crepes flambeadas com Grand Marnier', price: '$$', chefPick: true },
      { name: 'Coupe de Glace', description: 'Coupe de glaces au choix, chantilly', descriptionEn: 'Ice cream cup, choice of flavors, whipped cream', descriptionPt: 'Copo de sorvetes à escolha, chantilly', price: '$$' },
      { name: 'Dame Blanche', description: 'Dame blanche traditionnelle, glace vanille, crème Chantilly', descriptionEn: 'Traditional Dame Blanche, vanilla ice cream, Chantilly cream', descriptionPt: 'Dame Blanche tradicional, sorvete de baunilha, creme Chantilly', price: '$$' },
      { name: 'Gâteau Maison', description: 'Gâteau fait maison du jour', descriptionEn: 'Homemade cake of the day', descriptionPt: 'Bolo caseiro do dia', price: '$$' },
      { name: 'Cappuccino', description: 'Cappuccino italien', descriptionEn: 'Italian cappuccino', descriptionPt: 'Cappuccino italiano', price: '$' },
      { name: 'Irish Coffee', description: 'Irish coffee au whisky irlandais', descriptionEn: 'Irish coffee with Irish whiskey', descriptionPt: 'Irish coffee com whisky irlandês', price: '$$' },
      { name: 'Thé', description: 'Thé au choix', descriptionEn: 'Tea of your choice', descriptionPt: 'Chá à escolha', price: '$' },
      { name: 'Bica (Café Expresso)', description: 'Bica — café expresso portugais', descriptionEn: 'Bica — Portuguese espresso coffee', descriptionPt: 'Bica — café expresso português', price: '$' },
    ],
  },
];
